// Code generated by goyacc -l -o ./pkg/reduced_promql/parser/generated_parser.y.go ./pkg/reduced_promql/parser/generated_parser.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

type yySymType struct {
	yys  int
	str  string
	f64  float64
	expr Expr
	vec  *VectorSelector
	mat  *MatrixSelector
	lms  []LabelMatcher
	lm   LabelMatcher
	strs []string
	call *Call
	agg  *Aggregation
	grp  *Grouping
	pos  PosRange
}

const IDENT = 57346
const STRING = 57347
const NUMBER = 57348
const DURATION = 57349
const EQ = 57350
const NEQ = 57351
const RE = 57352
const NRE = 57353
const RATE = 57354
const COUNT = 57355
const SUM = 57356
const AVG = 57357
const MIN = 57358
const MAX = 57359
const HISTOGRAM_QUANTILE = 57360
const HEATMAP = 57361
const BY = 57362
const WITHOUT = 57363
const GROUP = 57364

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"STRING",
	"NUMBER",
	"DURATION",
	"EQ",
	"NEQ",
	"RE",
	"NRE",
	"RATE",
	"COUNT",
	"SUM",
	"AVG",
	"MIN",
	"MAX",
	"HISTOGRAM_QUANTILE",
	"HEATMAP",
	"BY",
	"WITHOUT",
	"GROUP",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"'['",
	"']'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

// You must provide a lexer that satisfies goyacc's expectations:
//
//	type Lexer interface {
//	  Lex(lval *promql_likeSymType) int
//	  Error(e string)
//	}
//
// Key lexer requirement for your dotted label keys:
// - scan runes (UTF-8)
// - accept '.' as part of IDENT so `req.status` becomes IDENT("req.status")
//
// Examples accepted:
//
//	{req.status = "500"}
//	prometheus{}
//	heatmap(prometheus{})
//	sum by (req.status) (rate({req.status="500"}[1m]))
//
// Examples rejected because of the heatmap restriction:
//
//	heatmap(rate(prometheus{}[5m]))
//	heatmap(prometheus{}[5m])
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 90

var yyAct = [...]int8{
	2, 37, 18, 35, 16, 14, 61, 79, 71, 54,
	11, 10, 6, 7, 8, 9, 12, 13, 33, 73,
	32, 17, 74, 19, 88, 53, 34, 85, 84, 18,
	47, 48, 83, 82, 81, 80, 78, 49, 52, 77,
	60, 72, 70, 51, 66, 67, 68, 69, 64, 65,
	19, 22, 24, 23, 50, 46, 75, 45, 44, 43,
	42, 41, 40, 39, 31, 30, 29, 56, 57, 58,
	59, 20, 86, 76, 87, 38, 63, 21, 3, 25,
	26, 27, 28, 4, 62, 55, 36, 15, 5, 1,
}

var yyPact = [...]int16{
	-2, -1000, -1000, -1000, -1000, -1000, 31, 31, 31, 31,
	31, 43, 42, 41, -7, -1000, -1000, -2, 1, 71,
	40, -1000, 39, 38, 37, 36, 35, 34, 32, -2,
	-2, 25, 47, 19, 71, -1, -20, -1000, 59, -2,
	72, 72, 72, -2, -2, -2, -2, 18, -21, 17,
	-9, -1000, -4, -1000, 71, 68, -1000, -1000, -1000, -1000,
	15, 12, -22, -1000, 11, 10, 9, 8, 4, 3,
	-1000, -2, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 70,
	-1000, -1000, -1000, -1000, -1000, -1000, 0, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 89, 0, 88, 5, 87, 3, 86, 1, 85,
	6, 84, 83, 78, 71, 77,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 3, 3, 3, 3, 4,
	4, 4, 5, 6, 6, 7, 7, 8, 9, 9,
	9, 9, 12, 12, 12, 13, 13, 13, 13, 13,
	14, 14, 15, 15, 15, 10, 10, 11, 11,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 3, 4,
	3, 1, 4, 0, 1, 1, 3, 3, 1, 1,
	1, 1, 4, 6, 4, 5, 5, 5, 5, 5,
	0, 1, 4, 4, 4, 0, 1, 1, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, -13, -12, -3, 14, 15, 16, 17,
	13, 12, 18, 19, -4, -5, 6, 23, 4, 25,
	-14, -15, 20, 22, 21, -14, -14, -14, -14, 23,
	23, 23, 27, -2, 25, -6, -7, -8, 4, 23,
	23, 23, 23, 23, 23, 23, 23, -2, -2, -4,
	7, 24, -6, 26, 29, -9, 8, 9, 10, 11,
	-2, -10, -11, 4, -10, -10, -2, -2, -2, -2,
	24, 29, 24, 28, 26, -8, 5, 24, 24, 29,
	24, 24, 24, 24, 24, 24, -2, 4, 24,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 30, 30, 30, 30,
	30, 0, 0, 0, 5, 6, 7, 0, 11, 13,
	0, 31, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 13, 0, 14, 15, 0, 0,
	35, 35, 35, 0, 0, 0, 0, 0, 0, 0,
	0, 8, 0, 10, 0, 0, 18, 19, 20, 21,
	0, 0, 36, 37, 0, 0, 0, 0, 0, 0,
	22, 0, 24, 12, 9, 16, 17, 25, 32, 0,
	33, 34, 26, 27, 28, 29, 0, 38, 23,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	23, 24, 3, 3, 29, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 27, 3, 28, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 25, 3, 26,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			Result = yyDollar[1].expr
			yyVAL.expr = yyDollar[1].expr
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].agg
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].call
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].vec
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].mat
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = Scalar{Val: yyDollar[1].f64}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			m := yyDollar[1].str
			yyVAL.vec = &VectorSelector{Metric: &m, Matchers: yyDollar[3].lms}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.vec = &VectorSelector{Metric: nil, Matchers: yyDollar[2].lms}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			m := yyDollar[1].str
			yyVAL.vec = &VectorSelector{Metric: &m, Matchers: nil}
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.mat = &MatrixSelector{Vector: yyDollar[1].vec, RangeStr: yyDollar[3].str}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.lms = nil
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.lms = yyDollar[1].lms
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.lms = []LabelMatcher{yyDollar[1].lm}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.lms = append(yyDollar[1].lms, yyDollar[3].lm)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.lm = LabelMatcher{Name: yyDollar[1].str, Op: yyDollar[2].str, Value: yyDollar[3].str}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = "="
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = "!="
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = "=~"
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = "!~"
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.call = &Call{Func: "rate", Args: []Expr{yyDollar[3].expr}}
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.call = &Call{Func: "histogram_quantile", Args: []Expr{yyDollar[3].expr, yyDollar[5].expr}}
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.call = &Call{Func: "heatmap", Args: []Expr{yyDollar[3].vec}}
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.agg = &Aggregation{Op: "sum", Grouping: yyDollar[2].grp, Expr: yyDollar[4].expr}
		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.agg = &Aggregation{Op: "avg", Grouping: yyDollar[2].grp, Expr: yyDollar[4].expr}
		}
	case 27:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.agg = &Aggregation{Op: "min", Grouping: yyDollar[2].grp, Expr: yyDollar[4].expr}
		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.agg = &Aggregation{Op: "max", Grouping: yyDollar[2].grp, Expr: yyDollar[4].expr}
		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.agg = &Aggregation{Op: "count", Grouping: yyDollar[2].grp, Expr: yyDollar[4].expr}
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.grp = nil
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.grp = yyDollar[1].grp
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.grp = &Grouping{Kind: "by", Keys: yyDollar[3].strs}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.grp = &Grouping{Kind: "by", Keys: yyDollar[3].strs}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.grp = &Grouping{Kind: "without", Keys: yyDollar[3].strs}
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.strs = nil
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strs = yyDollar[1].strs
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
